version: '3.1'

services:
  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_ADDRESS: ":50051"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database
      - pubsub

  email-service:
    build: ./email-service
    ports:
      - 50054:50051
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_ADDRESS: ":50051"
    depends_on:
      - pubsub

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

  pubsub:
    image: nats
    ports:
      - 4222:4222