// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

package go_micro_srv_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type CreateResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Vessel               *Vessel  `protobuf:"bytes,2,opt,name=vessel,proto3" json:"vessel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateResponse) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

type VesselResponse struct {
	Vessel               *Vessel  `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VesselResponse) Reset()         { *m = VesselResponse{} }
func (m *VesselResponse) String() string { return proto.CompactTextString(m) }
func (*VesselResponse) ProtoMessage()    {}
func (*VesselResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{3}
}

func (m *VesselResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VesselResponse.Unmarshal(m, b)
}
func (m *VesselResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VesselResponse.Marshal(b, m, deterministic)
}
func (m *VesselResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VesselResponse.Merge(m, src)
}
func (m *VesselResponse) XXX_Size() int {
	return xxx_messageInfo_VesselResponse.Size(m)
}
func (m *VesselResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VesselResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VesselResponse proto.InternalMessageInfo

func (m *VesselResponse) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.vessel.CreateResponse")
	proto.RegisterType((*VesselResponse)(nil), "go.micro.srv.vessel.VesselResponse")
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor_04ef66862bb50716) }

var fileDescriptor_04ef66862bb50716 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0x66, 0xfb, 0x43, 0x29, 0xf3, 0x0b, 0x87, 0xf5, 0xb2, 0xa0, 0x26, 0x64, 0xbd, 0x70, 0xaa,
	0x09, 0x3c, 0x81, 0x31, 0x9a, 0xe8, 0x71, 0x49, 0x34, 0xf1, 0x42, 0x96, 0xed, 0x88, 0x93, 0xd0,
	0x6e, 0xd3, 0x36, 0x05, 0xdf, 0xc6, 0x37, 0xf1, 0xd5, 0x4c, 0xb6, 0x05, 0x52, 0x83, 0xc4, 0xd3,
	0xce, 0x7c, 0xb3, 0xf3, 0xed, 0x37, 0xdf, 0x2c, 0x0c, 0xd3, 0xcc, 0x16, 0xf6, 0xa6, 0xc4, 0x3c,
	0xc7, 0x75, 0x7d, 0x84, 0x0e, 0xe3, 0xe7, 0x2b, 0x1b, 0xc6, 0x64, 0x32, 0x1b, 0xe6, 0x59, 0x19,
	0x56, 0x25, 0xf9, 0xc9, 0xc0, 0x7f, 0x76, 0x21, 0x1f, 0x80, 0x47, 0x91, 0x60, 0x63, 0x36, 0xe9,
	0x29, 0x8f, 0x22, 0x3e, 0x82, 0xc0, 0xe8, 0x54, 0x1b, 0x2a, 0x3e, 0x84, 0x37, 0x66, 0x93, 0x8e,
	0xda, 0xe7, 0xfc, 0x0a, 0x20, 0xd6, 0xdb, 0xc5, 0x06, 0x69, 0xf5, 0x5e, 0x88, 0x7f, 0xae, 0xda,
	0x8b, 0xf5, 0xf6, 0xc5, 0x01, 0x9c, 0x43, 0x3b, 0xd1, 0x31, 0x8a, 0xb6, 0x23, 0x73, 0x31, 0xbf,
	0x84, 0x9e, 0x2e, 0x35, 0xad, 0xf5, 0x72, 0x8d, 0xa2, 0x33, 0x66, 0x93, 0x40, 0x1d, 0x00, 0x3e,
	0x84, 0xc0, 0x6e, 0x12, 0xcc, 0x16, 0x14, 0x09, 0xdf, 0x75, 0x75, 0x5d, 0xfe, 0x18, 0xc9, 0x27,
	0xe8, 0xcf, 0x53, 0x34, 0xf4, 0x46, 0x46, 0x17, 0x64, 0x93, 0x86, 0x30, 0x76, 0x52, 0x98, 0xf7,
	0x43, 0x98, 0x5c, 0xc0, 0xe0, 0x2e, 0x43, 0x5d, 0xa0, 0xc2, 0x3c, 0xb5, 0x49, 0x8e, 0x5c, 0x40,
	0xd7, 0x38, 0xa4, 0x1a, 0x3d, 0x50, 0xbb, 0x94, 0xcf, 0xc0, 0xaf, 0x4c, 0x72, 0x34, 0xff, 0xa7,
	0x17, 0xe1, 0x11, 0x03, 0xc3, 0xca, 0x3c, 0x55, 0x5f, 0x95, 0xf7, 0x30, 0xa8, 0x91, 0xdd, 0x03,
	0x07, 0x1a, 0xf6, 0x67, 0x9a, 0xe9, 0x17, 0x83, 0x7e, 0x05, 0xcd, 0x31, 0x2b, 0xc9, 0x20, 0x57,
	0x70, 0x56, 0x29, 0xaf, 0xb7, 0x75, 0x8a, 0x66, 0x74, 0x7d, 0xb4, 0xd8, 0x9c, 0x5c, 0xb6, 0xf8,
	0x2b, 0xf4, 0x1f, 0x28, 0x89, 0x6e, 0xf7, 0x5b, 0x90, 0x47, 0xfb, 0x1a, 0xee, 0xff, 0xc2, 0xdd,
	0x1c, 0x5a, 0xb6, 0x96, 0xbe, 0xfb, 0x74, 0xb3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x40,
	0xf1, 0x8a, 0x91, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	CreateVessel(ctx context.Context, in *Vessel, opts ...client.CallOption) (*CreateResponse, error)
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*VesselResponse, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) CreateVessel(ctx context.Context, in *Vessel, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.CreateVessel", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*VesselResponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(VesselResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	CreateVessel(context.Context, *Vessel, *CreateResponse) error
	FindAvailable(context.Context, *Specification, *VesselResponse) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) CreateVessel(ctx context.Context, in *Vessel, out *CreateResponse) error {
	return h.VesselServiceHandler.CreateVessel(ctx, in, out)
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *VesselResponse) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}
